### ISSUE TITLE
Compare to SlateJS?

### ISSUE THREAD

**Issue by linonetwo** [inokawa/rich-textarea#15]
Can you make a compare about tech differenct and decisions between rich-textarea and slatejs?

**Comment by inokawa** [comment]
Hi, thank you for interested in my library!
Here is my opinion,

Slate `inputs from contenteditable` and `outputs to contenteditable dom`.
rich-textarea `inputs from textarea` and `outputs to dom`, which is overlayed by transparent textarea and the texts are layouted exactly same as textarea.

As well known, contenteditable has many crossplatform problems so it's harder to develop with it, textarea is much stable.

What rich-textarea can do is limited and Slate can do much more. It's because the core of this library is transparent textarea. The texts must be layouted the same as textarea and same sized.
For example, you can not change font-size by letters. It's impossible to make Word or Google docs with rich-texarea, but may be possible with Slate.

However textarea is easier to use in some cases because it's simple. And I can add some option to this library if it's useful and it's possible with textarea.
And Slate is 8x larger this library. See https://bundlephobia.com/package/rich-textarea

**Comment by linonetwo** [comment]
I see! Surely rich-textarea have advantages when choosing libraries, thanks for the explaination!explanation
