### ISSUE TITLE
[feature] When the cursor is to the right of Mention, press the Delete key to delete the entire Mention  

### ISSUE THREAD

**Issue by GOWxx** [inokawa/rich-textarea#16]
Expect the entire Mention to be treated as a whole

**Comment by inokawa** [comment]
Hi,
You can get caret offset with `onSelectionChange` prop, so you can achieve the behavior if you slice text state when the carret offset is under the mention range.

I know it's bit complicated but I don't think I could implement it as core, because this library is not only for mention.
However it's nice to implement a helper function or component to achieve the behavior easily, or add some example which helps to implement it.

**Comment by GOWxx** [comment]
> 

thank you for your reply ^ ^
